version: 2
orbs:
  ruby: circleci/ruby@0.1.2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-stretch-node
    steps:
      - checkout
      - run: gem install bundler:2.1.4
      - run: bundle init
      - run: cat Gemfile 
      # - run: bundle install
      # - run: bundle exec danger init