version: 2
orbs:
  ruby: circleci/ruby@0.1.2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-stretch-node
    steps:
      - checkout
      - run: gem install bundler:2.1.4
      - restore_cache:
          key: gems-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      # - run: bundle init
      - run: echo gem \"danger\" >> Gemfile 
      # - run: cat Gemfile
      - run: bundle install
      - run: bundle exec danger